# Generated by Django 3.2.3 on 2022-02-01 14:35

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_el', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('address_en', models.CharField(max_length=50, null=True, verbose_name='Address')),
                ('address_el', models.CharField(max_length=50, null=True, verbose_name='Address')),
                ('pobox', models.CharField(max_length=5, verbose_name='Pobox')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('city_en', models.CharField(max_length=64, null=True, verbose_name='City')),
                ('city_el', models.CharField(max_length=64, null=True, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('country_en', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('country_el', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('telephone', models.CharField(max_length=10, validators=[utils.validators.telephone_validator], verbose_name='Telephone')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_el', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('address_en', models.CharField(max_length=50, null=True, verbose_name='Address')),
                ('address_el', models.CharField(max_length=50, null=True, verbose_name='Address')),
                ('pobox', models.CharField(max_length=5, verbose_name='Pobox')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('city_en', models.CharField(max_length=64, null=True, verbose_name='City')),
                ('city_el', models.CharField(max_length=64, null=True, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('country_en', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('country_el', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('telephone', models.CharField(max_length=10, validators=[utils.validators.telephone_validator], verbose_name='Telephone')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
    ]
