# Generated by Django 3.2.3 on 2021-12-21 14:02

from django.db import migrations, models
import django.db.models.deletion
import institution.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en_us', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_el_GR', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('address_en_us', models.CharField(max_length=50, null=True, verbose_name='Address')),
                ('address_el_GR', models.CharField(max_length=50, null=True, verbose_name='Address')),
                ('pobox', models.CharField(max_length=5, verbose_name='Pobox')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('city_en_us', models.CharField(max_length=64, null=True, verbose_name='City')),
                ('city_el_GR', models.CharField(max_length=64, null=True, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('country_en_us', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('country_el_GR', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('telephone', models.CharField(max_length=10, validators=[institution.validators.only_int], verbose_name='Telephone')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en_us', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_el_GR', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('address_en_us', models.CharField(max_length=50, null=True, verbose_name='Address')),
                ('address_el_GR', models.CharField(max_length=50, null=True, verbose_name='Address')),
                ('pobox', models.CharField(max_length=5, verbose_name='Pobox')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('city_en_us', models.CharField(max_length=64, null=True, verbose_name='City')),
                ('city_el_GR', models.CharField(max_length=64, null=True, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('country_en_us', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('country_el_GR', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('telephone', models.CharField(max_length=10, validators=[institution.validators.only_int], verbose_name='Telephone')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution', verbose_name='Institution')),
            ],
        ),
    ]
