# Generated by Django 3.2.3 on 2022-02-01 18:25

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='secretary', serialize=False, to='user_account.user')),
                ('telephone', models.CharField(max_length=10, validators=[utils.validators.telephone_validator], verbose_name='Telephone')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.department')),
            ],
            options={
                'verbose_name': 'Secretary',
                'verbose_name_plural': 'Secretaries',
            },
        ),
    ]
