version: '3.6'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            python manage.py migrate --noinput &&
              gunicorn mscApplications.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/
      - static_volume:/usr/src/staticfiles
      - media_volume:/usr/src/mediafiles
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file: .env.db
    ports:
      - 5432
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/staticfiles
      - media_volume:/usr/src/mediafiles
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: