# Generated by Django 3.2.3 on 2022-01-01 15:00

import applicant.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('msc', '0001_initial'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='applicant', serialize=False, to='user_account.user')),
                ('telephone', models.CharField(blank=True, max_length=10, null=True, validators=[utils.validators.telephone_validator], verbose_name='Telephone')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Gender')),
                ('citizenship', models.CharField(blank=True, max_length=64, null=True, verbose_name='Citizenship')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(auto_now_add=True, verbose_name='Submission Date')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('admitted', models.BooleanField(blank=True, default=None, null=True, verbose_name='Admitted')),
                ('media_file', models.FileField(upload_to=applicant.utils.application_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Media File')),
                ('admitted_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admitted_application', to='msc.mscflow')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msc.call')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200, verbose_name='Organization')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('job_title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('telephone', models.CharField(max_length=10, verbose_name='Telephone')),
                ('reference_date', models.DateField(verbose_name='Reference Date')),
                ('media_file', models.FileField(upload_to=applicant.utils.reference_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Media File')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(verbose_name='Priority')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.application')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msc.mscflow')),
            ],
            options={
                'verbose_name': 'Priority',
                'verbose_name_plural': 'Priorities',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Phd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', ''), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2, verbose_name='Type')),
                ('awarding_institution', models.CharField(max_length=200, verbose_name='Awarding Institution')),
                ('department', models.CharField(max_length=200, verbose_name='Department')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('supervisor', models.CharField(max_length=64, verbose_name='Supervisor')),
                ('date_awarded', models.DateField(verbose_name='Date Awarded')),
                ('grade_point_average', models.IntegerField(verbose_name='Average Grade')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('media_file', models.FileField(upload_to=applicant.utils.phd_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Media File')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
            ],
            options={
                'verbose_name': 'PHD',
                'verbose_name_plural': 'PHDs',
            },
        ),
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200, verbose_name='Organization')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('job_title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('media_file', models.FileField(upload_to=applicant.utils.job_experience_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Media File')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
            ],
            options={
                'verbose_name': 'Job Experience',
                'verbose_name_plural': 'Job Experiences',
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', ''), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2, verbose_name='Type')),
                ('awarding_institution', models.CharField(max_length=200, verbose_name='Awarding Institution')),
                ('department', models.CharField(max_length=200, verbose_name='Department')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Specialization')),
                ('date_awarded', models.DateField(verbose_name='Date Awarded')),
                ('grade_point_average', models.IntegerField(verbose_name='Average Grade')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('media_file', models.FileField(upload_to=applicant.utils.diploma_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Media File')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
            ],
            options={
                'verbose_name': 'Diploma',
                'verbose_name_plural': 'Diplomas',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='preferences',
            field=models.ManyToManyField(blank=True, related_name='waiting_applications', through='applicant.Preference', to='msc.MscFlow'),
        ),
        migrations.AddField(
            model_name='application',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.reference'),
        ),
    ]
