# Generated by Django 3.2.3 on 2021-12-22 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msc', '0001_initial'),
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='applicant', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='admitted_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admitted_application', to='msc.mscflow'),
        ),
        migrations.AlterField(
            model_name='application',
            name='preferences',
            field=models.ManyToManyField(blank=True, related_name='waiting_applications', through='applicant.Preference', to='msc.MscFlow'),
        ),
        migrations.AlterField(
            model_name='application',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.reference'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='grade_point_average',
            field=models.IntegerField(verbose_name='Average Grade'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='type',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], default='UG', max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant'),
        ),
        migrations.AlterField(
            model_name='phd',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant'),
        ),
        migrations.AlterField(
            model_name='phd',
            name='grade_point_average',
            field=models.IntegerField(verbose_name='Average Grade'),
        ),
        migrations.AlterField(
            model_name='phd',
            name='type',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], default='UG', max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.application'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msc.mscflow'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant'),
        ),
    ]
