# Generated by Django 3.2.3 on 2021-12-25 04:15

import applicant.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_auto_20211224_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='citizenship',
            field=models.CharField(blank=True, max_length=64, verbose_name='Citizenship'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='city',
            field=models.CharField(blank=True, max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, validators=[applicant.validators.only_int], verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='type',
            field=models.CharField(choices=[('', ''), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='phd',
            name='type',
            field=models.CharField(choices=[('', ''), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2, verbose_name='Type'),
        ),
    ]
