# Generated by Django 3.2.3 on 2021-12-21 14:02

from django.db import migrations, models
import django.db.models.deletion
import evaluator.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0001_initial'),
        ('msc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='evaluator', serialize=False, to='user_account.user', verbose_name='User')),
                ('telephone', models.CharField(max_length=10, validators=[evaluator.validators.only_int], verbose_name='Telephone')),
                ('committee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='msc.call', verbose_name='Committe')),
            ],
        ),
    ]
