# Generated by Django 3.2.3 on 2021-12-22 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msc', '0001_initial'),
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluator',
            name='committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='msc.call'),
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='evaluator', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
