# Generated by Django 3.2.3 on 2022-02-01 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import msc.utils
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(auto_now_add=True, verbose_name='Submission Date')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('admitted', models.BooleanField(blank=True, default=None, null=True, verbose_name='Admitted')),
                ('media_file', models.FileField(upload_to=msc.utils.application_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Media File')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_el', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Call',
                'verbose_name_plural': 'Calls',
            },
        ),
        migrations.CreateModel(
            name='MscFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_el', models.CharField(max_length=200, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'MSC Flow',
                'verbose_name_plural': 'MSC Flows',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(verbose_name='Priority')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msc.application')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msc.mscflow')),
            ],
            options={
                'verbose_name': 'Priority',
                'verbose_name_plural': 'Priorities',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='MscProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_el', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('address_en', models.CharField(max_length=50, null=True, verbose_name='Address')),
                ('address_el', models.CharField(max_length=50, null=True, verbose_name='Address')),
                ('pobox', models.CharField(max_length=5, verbose_name='Pobox')),
                ('city', models.CharField(max_length=65, verbose_name='City')),
                ('city_en', models.CharField(max_length=65, null=True, verbose_name='City')),
                ('city_el', models.CharField(max_length=65, null=True, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('country_en', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('country_el', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('telephone', models.CharField(max_length=10, validators=[utils.validators.telephone_validator], verbose_name='Telephone')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'MSC Programme',
                'verbose_name_plural': 'MSC Programmes',
            },
        ),
        migrations.AddField(
            model_name='mscflow',
            name='msc_programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msc.mscprogramme', verbose_name='Msc Programme'),
        ),
    ]
