# Generated by Django 3.2.3 on 2021-12-30 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluator', '0001_initial'),
        ('msc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='evaluators',
            field=models.ManyToManyField(to='evaluator.Evaluator'),
        ),
        migrations.AddField(
            model_name='call',
            name='msc_programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msc.mscprogramme', verbose_name='Msc Programme'),
        ),
    ]
