# Generated by Django 3.2.3 on 2022-02-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mscprogramme',
            name='pobox',
        ),
        migrations.RemoveField(
            model_name='mscprogramme',
            name='telephone',
        ),
        migrations.AddField(
            model_name='mscprogramme',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
