# Generated by Django 3.2.3 on 2022-02-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0003_auto_20220212_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscprogramme',
            name='description_el',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='mscprogramme',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
