# Generated by Django 3.2.3 on 2022-02-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0004_auto_20220212_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mscprogramme',
            name='address_el',
        ),
        migrations.RemoveField(
            model_name='mscprogramme',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='mscprogramme',
            name='city',
        ),
        migrations.RemoveField(
            model_name='mscprogramme',
            name='city_el',
        ),
        migrations.RemoveField(
            model_name='mscprogramme',
            name='city_en',
        ),
        migrations.RemoveField(
            model_name='mscprogramme',
            name='country',
        ),
        migrations.RemoveField(
            model_name='mscprogramme',
            name='country_el',
        ),
        migrations.RemoveField(
            model_name='mscprogramme',
            name='country_en',
        ),
    ]
