# Generated by Django 3.2.3 on 2022-02-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0005_auto_20220212_2014'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('applicant', 'call'), name='unique call for applicant'),
        ),
    ]
