# Generated by Django 3.2.3 on 2021-06-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='title_el_GR',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='call',
            name='title_en_us',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='mscflow',
            name='title_el_GR',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='mscflow',
            name='title_en_us',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='mscprogramme',
            name='address_el_GR',
            field=models.CharField(max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='mscprogramme',
            name='address_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='mscprogramme',
            name='city_el_GR',
            field=models.CharField(max_length=64, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='mscprogramme',
            name='city_en_us',
            field=models.CharField(max_length=64, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='mscprogramme',
            name='country_el_GR',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='mscprogramme',
            name='country_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='mscprogramme',
            name='pobox_el_GR',
            field=models.CharField(max_length=5, null=True, verbose_name='Pobox'),
        ),
        migrations.AddField(
            model_name='mscprogramme',
            name='pobox_en_us',
            field=models.CharField(max_length=5, null=True, verbose_name='Pobox'),
        ),
        migrations.AddField(
            model_name='mscprogramme',
            name='telephone_el_GR',
            field=models.CharField(max_length=10, null=True, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='mscprogramme',
            name='telephone_en_us',
            field=models.CharField(max_length=10, null=True, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='mscprogramme',
            name='title_el_GR',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='mscprogramme',
            name='title_en_us',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
