# Generated by Django 3.2.3 on 2021-06-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0002_auto_20210616_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mscprogramme',
            name='pobox_el_GR',
        ),
        migrations.RemoveField(
            model_name='mscprogramme',
            name='pobox_en_us',
        ),
        migrations.RemoveField(
            model_name='mscprogramme',
            name='telephone_el_GR',
        ),
        migrations.RemoveField(
            model_name='mscprogramme',
            name='telephone_en_us',
        ),
    ]
