# Generated by Django 3.2.3 on 2021-06-16 20:52

from django.db import migrations, models
import msc.models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0005_auto_20210616_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluator',
            name='telephone',
            field=models.CharField(max_length=10, validators=[msc.models.only_int], verbose_name='Telephone'),
        ),
    ]
