# Generated by Django 3.2.3 on 2021-06-22 16:59

from django.db import migrations, models
import msc.models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0006_alter_evaluator_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mscprogramme',
            name='telephone',
            field=models.CharField(max_length=10, validators=[msc.models.only_int], verbose_name='Telephone'),
        ),
    ]
