# Generated by Django 3.2.3 on 2021-06-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0007_alter_mscprogramme_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mscprogramme',
            name='city',
            field=models.CharField(max_length=65, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='mscprogramme',
            name='city_el_GR',
            field=models.CharField(max_length=65, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='mscprogramme',
            name='city_en_us',
            field=models.CharField(max_length=65, null=True, verbose_name='City'),
        ),
    ]
