# Generated by Django 3.2.3 on 2021-06-16 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('msc', '0001_initial'),
        ('applicant_degrees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msc.mscflow', verbose_name='Flow'),
        ),
        migrations.AddField(
            model_name='phd',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant_degrees.applicant', verbose_name='Applicant'),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant_degrees.applicant', verbose_name='Applicant'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant_degrees.applicant', verbose_name='Applicant'),
        ),
        migrations.AddField(
            model_name='application',
            name='admitted_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admitted_application', to='msc.mscflow', verbose_name='Admitted FLow'),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant_degrees.applicant'),
        ),
        migrations.AddField(
            model_name='application',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msc.call'),
        ),
        migrations.AddField(
            model_name='application',
            name='preferences',
            field=models.ManyToManyField(blank=True, related_name='waiting_applications', through='applicant_degrees.Preference', to='msc.MscFlow', verbose_name='Preferences'),
        ),
        migrations.AddField(
            model_name='application',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant_degrees.reference', verbose_name='Reference'),
        ),
    ]
