# Generated by Django 3.2.3 on 2021-06-16 20:52

import applicant_degrees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_degrees', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='telephone',
            field=models.CharField(max_length=10, validators=[applicant_degrees.models.only_int], verbose_name='Telephone'),
        ),
    ]
