# Generated by Django 3.2.3 on 2021-06-16 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='address_el_GR',
            field=models.CharField(max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='department',
            name='address_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='department',
            name='city_el_GR',
            field=models.CharField(max_length=64, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='department',
            name='city_en_us',
            field=models.CharField(max_length=64, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='department',
            name='country_el_GR',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='department',
            name='country_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='department',
            name='institution_el_GR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.institution', verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='department',
            name='institution_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.institution', verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='department',
            name='pobox_el_GR',
            field=models.CharField(max_length=5, null=True, verbose_name='Pobox'),
        ),
        migrations.AddField(
            model_name='department',
            name='pobox_en_us',
            field=models.CharField(max_length=5, null=True, verbose_name='Pobox'),
        ),
        migrations.AddField(
            model_name='department',
            name='telephone_el_GR',
            field=models.CharField(max_length=10, null=True, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='department',
            name='telephone_en_us',
            field=models.CharField(max_length=10, null=True, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='department',
            name='title_el_GR',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='department',
            name='title_en_us',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='institution',
            name='address_el_GR',
            field=models.CharField(max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='institution',
            name='address_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='institution',
            name='city_el_GR',
            field=models.CharField(max_length=64, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='institution',
            name='city_en_us',
            field=models.CharField(max_length=64, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='institution',
            name='country_el_GR',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='institution',
            name='country_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='institution',
            name='pobox_el_GR',
            field=models.CharField(max_length=5, null=True, verbose_name='Pobox'),
        ),
        migrations.AddField(
            model_name='institution',
            name='pobox_en_us',
            field=models.CharField(max_length=5, null=True, verbose_name='Pobox'),
        ),
        migrations.AddField(
            model_name='institution',
            name='telephone_el_GR',
            field=models.CharField(max_length=10, null=True, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='institution',
            name='telephone_en_us',
            field=models.CharField(max_length=10, null=True, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='institution',
            name='title_el_GR',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='institution',
            name='title_en_us',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
