# Generated by Django 3.2.3 on 2021-06-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_auto_20210616_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='institution_el_GR',
        ),
        migrations.RemoveField(
            model_name='department',
            name='institution_en_us',
        ),
    ]
