# Generated by Django 3.2.3 on 2021-06-16 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_auto_20210616_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='address_el_GR',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='address_en_us',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='department',
            name='city_el_GR',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='city_en_us',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='country_el_GR',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='country_en_us',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
        migrations.AlterField(
            model_name='department',
            name='pobox',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='department',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='title_el_GR',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='title_en_us',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address_el_GR',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address_en_us',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='institution',
            name='city_el_GR',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='city_en_us',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country_el_GR',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country_en_us',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='pobox',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='institution',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='institution',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='institution',
            name='title_el_GR',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='title_en_us',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
