# Generated by Django 3.2.3 on 2021-06-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_auto_20210616_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='department',
            name='address_el_GR',
            field=models.CharField(max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='department',
            name='address_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='department',
            name='city',
            field=models.CharField(max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='department',
            name='city_el_GR',
            field=models.CharField(max_length=64, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='department',
            name='city_en_us',
            field=models.CharField(max_length=64, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='department',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='department',
            name='country_el_GR',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='department',
            name='country_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='department',
            name='pobox',
            field=models.CharField(max_length=5, verbose_name='Pobox'),
        ),
        migrations.AlterField(
            model_name='department',
            name='telephone',
            field=models.CharField(max_length=10, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title_el_GR',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title_en_us',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address_el_GR',
            field=models.CharField(max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='city',
            field=models.CharField(max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='city_el_GR',
            field=models.CharField(max_length=64, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='city_en_us',
            field=models.CharField(max_length=64, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country_el_GR',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='pobox',
            field=models.CharField(max_length=5, verbose_name='Pobox'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='telephone',
            field=models.CharField(max_length=10, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='title_el_GR',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='title_en_us',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
