# Generated by Django 3.2.3 on 2021-06-17 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_auto_20210616_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution', verbose_name='Institution'),
        ),
    ]
