# Generated by Django 3.2.3 on 2021-06-22 16:59

from django.db import migrations, models
import institution.models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_alter_department_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='telephone',
            field=models.CharField(max_length=10, validators=[institution.models.only_int], verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='telephone',
            field=models.CharField(max_length=10, validators=[institution.models.only_int], verbose_name='Telephone'),
        ),
    ]
