# Generated by Django 3.2.3 on 2022-02-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_secretary',
            field=models.BooleanField(default=False),
        ),
    ]
